TestApp/Models/RELATIVES.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]   
    public partial class Relatives
    {
        public string SurName { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Address { get; set; }
        public int ID { get; set; }
        public Nullable<int> MotherID { get; set; }
        public Nullable<int> FatherID { get; set; }
        public string Sex { get; set; }
    }
}

TestApp/Controllers/RelativesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestApp.Models;
using System.Xml.Serialization;
using System.IO;


namespace TestApp.Controllers
{
    public class RelativesController : Controller
    {

        private prcs_testAppEntities db = new prcs_testAppEntities();

        //
        // GET: /Relatives/



        public ActionResult Index(string type="vis")
        {
            List<Relatives> arRelatives = db.Relatives.ToList();
            switch (type)
            {
                case "json":
                    try
                    {
                        
                        return Json(new { Result = "OK", Records = arRelatives }, JsonRequestBehavior.AllowGet);
                    }
                    catch (Exception ex)
                    {
                        return Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
                    };
                case "xml":
                    try
                    {
                        XmlSerializer ser = new XmlSerializer(typeof(List<Relatives>));
                        using(var stream = new StringWriter())
                        {
                            ser.Serialize(stream, arRelatives);
                            return Content(stream.GetStringBuilder().ToString());
                        }
                        
                    }
                    catch(Exception ex)
                    {
                        List<string> list = new List<string>() { "ERROR",ex.Message };
                        XmlSerializer ser = new XmlSerializer(typeof(List<string>));
                        using (var stream = new StringWriter())
                        {
                            ser.Serialize(stream, list);
                            return Content(stream.GetStringBuilder().ToString());
                        }
                        
                    };
                default:
                var SearchSex = new SelectList(new[]
                                          {
                                              new{ID="",Name=""},
                                              new {ID="F",Name="Female"},
                                              new{ID="M",Name="Male"}                                             
                                          },
                                        "ID", "Name", "");
                ViewData["SearchSex"] = SearchSex;
                return View(arRelatives);
            }

        }

        //
        // GET: /Relatives/Details/5

        public ActionResult Details(int id = 0, string type="vis")
        {
            Relatives Relatives = db.Relatives.Find(id);
            switch (type)
            {
                case "json":                   
                    if (Relatives == null)
                    {
                        return Json(new { Result = "ERROR", Message = "Empty Set" }, JsonRequestBehavior.AllowGet); ;
                    }
                    try
                    {
                        return Json(new { Result = "OK", Records = Relatives }, JsonRequestBehavior.AllowGet);
                    }
                    catch (Exception ex)
                    {
                        return Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
                    };
                case "xml":
                    try
                    {
                        XmlSerializer ser = new XmlSerializer(typeof(Relatives));
                        using (var stream = new StringWriter())
                        {
                            ser.Serialize(stream, Relatives);
                            return Content(stream.GetStringBuilder().ToString());
                        }

                    }
                    catch (Exception ex)
                    {
                        List<string> list = new List<string>() { "ERROR", ex.Message };
                        XmlSerializer ser = new XmlSerializer(typeof(List<string>));
                        using (var stream = new StringWriter())
                        {
                            ser.Serialize(stream, list);
                            return Content(stream.GetStringBuilder().ToString());
                        }

                    };
                default:
                    return View(Relatives);
            }

        }

        //
        // GET: /Relatives/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Relatives/Create

        [HttpPost]
        public ActionResult Create(Relatives Relatives)
        {
            if (ModelState.IsValid)
            {
                db.Relatives.Add(Relatives);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(Relatives);
        }

        //
        // GET: /Relatives/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Relatives Relatives = db.Relatives.Find(id);
            if (Relatives == null)
            {
                return HttpNotFound();
            }
            return View(Relatives);
        }

        //
        // POST: /Relatives/Edit/5

        [HttpPost]
        public ActionResult Edit(Relatives Relatives)
        {
            if (ModelState.IsValid)
            {
                db.Entry(Relatives).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Relatives);
        }

        //
        // GET: /Relatives/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Relatives Relatives = db.Relatives.Find(id);
            if (Relatives == null)
            {
                return HttpNotFound();
            }
            return View(Relatives);
        }

        //
        // POST: /Relatives/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Relatives Relatives = db.Relatives.Find(id);
            db.Relatives.Remove(Relatives);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Search(string SearchSURNAME, string SearchNAME, string SearchLASTNAME, string SearchBDATE)
        {

            var Relatives = from m in db.Relatives
                         select m;

            if (!String.IsNullOrEmpty(SearchSURNAME))
            {
                Relatives = Relatives.Where(s => s.SurName.Contains(SearchSURNAME));
            }
            if (!String.IsNullOrEmpty(SearchNAME))
            {
                Relatives = Relatives.Where(s => s.Name.Contains(SearchNAME));
            }
            if (!String.IsNullOrEmpty(SearchLASTNAME))
            {
                Relatives = Relatives.Where(s => s.LastName.Contains(SearchLASTNAME));
            }
            if (!String.IsNullOrEmpty(SearchBDATE))
            {
                DateTime BDATE = new DateTime();
                BDATE = DateTime.ParseExact(SearchBDATE,"dd.MM.yyyy",System.Globalization.CultureInfo.InvariantCulture);// (SearchBDATE);
                Relatives = Relatives.Where(s => s.BirthDate==BDATE);
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

TestApp/Views/Relatives/Create.cshtml
@model TestApp.Models.Relatives

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>RELATIVES</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.SurName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SurName)
            @Html.ValidationMessageFor(model => model.SurName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BirthDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BirthDate)
            @Html.ValidationMessageFor(model => model.BirthDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MotherID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MotherID)
            @Html.ValidationMessageFor(model => model.MotherID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FatherID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FatherID)
            @Html.ValidationMessageFor(model => model.FatherID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Sex)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Sex)
            @Html.ValidationMessageFor(model => model.Sex)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestApp/Views/Relatives/Delete.cshtml
@model TestApp.Models.Relatives

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>RELATIVES</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Surname)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Surname)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BirthDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BirthDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MotherID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MotherID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FatherID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FatherID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Sex)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Sex)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

TestApp/Views/Relatives/Details.cshtml
@model TestApp.Models.Relatives

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>RELATIVES</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SurName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SurName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BirthDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BirthDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MotherID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MotherID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FatherID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FatherID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Sex)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Sex)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TestApp/Views/Relatives/Edit.cshtml
@model TestApp.Models.Relatives

@{
    ViewBag.Title = "Edit";
}


  <script>
  $(function() {
      $("#BirthDate").datepicker({
          changeMonth: true,
          changeYear: true,
          dateFormat: 'dd.mm.yy'
      });
  });
  </script>
<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>RELATIVES</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.SurName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SurName)
            @Html.ValidationMessageFor(model => model.SurName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BirthDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BirthDate)
            @Html.ValidationMessageFor(model => model.BirthDate)       
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.MotherID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MotherID)
            @Html.ValidationMessageFor(model => model.MotherID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FatherID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FatherID)
            @Html.ValidationMessageFor(model => model.FatherID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Sex)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Sex)
            @Html.ValidationMessageFor(model => model.Sex)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestApp/Views/Relatives/Index.cshtml
@model IEnumerable<TestApp.Models.Relatives>

@{
    ViewBag.Title = "Index";
}
  <script>
  $(function() {
      $("#SearchBDate").datepicker({
          changeMonth: true,
          changeYear: true,
          dateFormat: 'dd.mm.yy'
      }).disableSelection();
  });
  </script>
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Search","Relatives")){
        <table>
            <tr>
                <th>
                    SurName: 
                </th>
                <th>
                    @Html.TextBox("SearchSurName") 
                </th>
            </tr>
            <tr>
                <th>
                    Name: 
                </th>
                <th>
                    @Html.TextBox("SearchName") 
                </th>
            </tr>
            <tr>
                <th>
                    LastName: 
                </th>
                <th>
                    @Html.TextBox("SearchLastName") 
                </th>
            </tr>
            <tr>
                <th>
                    BirthDate: 
                </th>
                <th>
                    @Html.TextBox("SearchBDate") 
                </th>
            </tr>
            <tr>
                <th>
                    Address: 
                </th>
                <th>
                    @Html.TextBox("SearchAddress") 
                </th>
            </tr>
            <tr>
                <th>
                    Sex: 
                </th>
                <th>
                    @Html.DropDownList("SearchSex", ViewData["SearchSex"] as SelectList) 
                   <!--
                    <select id="SearchSex" name="SearchSex">
                        <option value=""></option>
                        <option value="F">Female</option>
                        <option value="M">Male</option>
                    </select> 
                     -->
                </th>
            </tr>

        </table> 
    <input type="submit" value="Filter" />
} 
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SurName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MotherID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FatherID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sex)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SurName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirthDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MotherID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FatherID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sex)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>